DROP DATABASE IF EXISTS yun;
CREATE DATABASE yun;
USE yun;
CREATE TABLE yun_user(
  uid INT PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(11),
  pwd VARCHAR(16)
);
 INSERT INTO yun_user VALUES(1,13362030918,123456);
 SELECT*FROM yun_user;


